### ISSUE TITLE
Issue with remote: HTTP errors

### ISSUE THREAD

**Issue by R7788380** [TorchStudio/torchstudio#5]
I can connect to the remote host via ssh, but torchstudio doesn't work.

I have set remote configuration named AI_server like below,then it will install `Paramiko` python package to ssh server.

<img width="202" alt="螢幕擷取畫面 2022-03-03 103332" src="https://user-images.githubusercontent.com/23279866/156486652-8aa71df5-c107-4615-a819-3f43903cb90c.png">

But I get error message like below, it looks like there is not internet on localhost to install `Paramiko`, but I'm sure that the local network is working.

<img width="199" alt="螢幕擷取畫面 2022-03-03 103756" src="https://user-images.githubusercontent.com/23279866/156486869-6b40a593-be0e-4f30-9799-9925efe10287.png">

**Comment by divideconcept** [comment]
Do you still get the same error if you click **Refresh** ?

If it still doesn't work, you could install the missing Paramiko package manually (that's the only package that needs to be installed on the remote server).
Since you're on Windows, you can use Putty to connect to your SSH server. When you're in, type the path to conda to install paramiko. If your path to python is `PYTHONROOT/bin/python` then your path to conda will be `PYTHONROOT/condabin/conda`.
The command you have to type on your remote server is:
`PYTHONROOT/condabin/conda install paramiko -c conda-forge`
This will install paramiko. If all goes well then you can disconnect from your remote server and try TorchStudio refresh again.

**Comment by R7788380** [comment]
Thanks for your reply.
It works well after `conda install -c anaconda paramiko` on the remote server and click Refresh.
